services:
  # Caddy with simplified config
  caddy:
    image: caddy:2-alpine
    container_name: devwiki-caddy
    restart: unless-stopped
    ports:
      - "8000:80"
      - "4443:443"
    environment:
      - SERVER_IP=${SERVER_IP:-10.111.200.177}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/usr/share/caddy:ro
    networks:
      - wiki-network

networks:
  wiki-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
