services:
  caddy:
    image: caddy:2-alpine
    container_name: devwiki-caddy
    restart: unless-stopped
    ports:
      - "3003:443"
    environment:
      - SERVER_IP=localhost
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/usr/share/caddy:ro

volumes:
  caddy_data:
  caddy_config:
