baseURL = "http://localhost:1313"
languageCode = "en-us"

[markup.goldmark.renderer]
  unsafe = true  # Allows HTML in markdown

[params]
  BookTheme = "auto"
  BookMenuBundle = '/menu'
  BookSection = 'docs'
  BookLogo = "sev.svg"
  BookFavicon = "sev.svg"
  BookToC = true
