baseURL = "http://localhost:1313"
languageCode = "en-us"
theme = "hugo-book"  # This line is crucial

[params]
  BookTheme = "auto"
  BookSection = 'docs'
  BookLogo = "sev.svg"
  BookFavicon = "sev.svg"
  BookToC = true
