name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Hugo
        run: |
          # Skip if Hugo is already installed
          if ! command -v hugo &> /dev/null; then
            echo "Installing Hugo..."
            apt-get update && apt-get install -y hugo || apk add --no-cache hugo
          fi
      
      - name: Setup theme
        run: |
          git clone https://github.com/alex-shpak/hugo-book.git themes/hugo-book
      
      - name: Build and deploy
        run: |
          # Build the site
          hugo --minify
          
          # Copy to web directory
          rm -rf /var/www/hugo-site/*
          cp -r public/* /var/www/hugo-site/
          
          echo "Deployed to /var/www/hugo-site"